# Generated by Django 3.2.8 on 2022-04-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0003_alter_apikey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='new_api',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api',
            field=models.CharField(max_length=200),
        ),
    ]
