# Generated by Django 3.2.18 on 2023-03-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0005_auto_20220419_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api',
            field=models.CharField(max_length=200, verbose_name='Ключ API для сервиса статистики'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='new_api',
            field=models.CharField(default='', max_length=400, verbose_name='Ключ API стандартный'),
        ),
    ]
